### PR TITLE
Released version android-1.1.2

### LINKED ISSUE #17: Creating release + publish to gitt.io
Repo needs to be tagged and a release should be created using zipped files inside `/dist/`.

### PR DESCRIPTION
**Pull request by odahcam**
Resolves #17

### CODE REVIEW

**Comment by iotashan** [comment]
Will I need to create a tag or anything, or will just the PR work?

**Comment by odahcam** [comment]
I think PR should work, since I cannot merge the tag I created.

**Comment by iotashan** [comment]
Let me know if that works, or if I need to tag it myself, too.

**Comment by odahcam** [comment]
I think you will need to create the tag by yourself. :/

You can look at my fork and make it the same as the one I made, it will work. :)

**Comment by iotashan** [comment]
try now

**Comment by odahcam** [comment]
Very nice, tag is there, now we just need to wait and watch GitTio index this repo as a module. 🎉

**Pull request merged**
